name: Thundra CI Check

on:
  push:
    branches:
      - "test/ga-trial"
      - "master"
  pull_request:
    branches:
      - "test/ga-trial"
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 8.x
        uses: actions/setup-node@v2
        with:
          node-version: "8.x"
      - name: Start Docker Images
        run: docker-compose up -d --quiet-pull --no-recreate
      - name: NPM Install
        run: npm install
      - name: NPM Linter
        run: npm run lint
      - name: NPM Test CI
        run: npm run test-ga
